
# Make sure we have our ENV_PERSONALWEBSITE_DIR environment variable set.
if [ -z "$ENV_PERSONALWEBSITE_DIR" ]; then
    echo "Need to set ENV_PERSONALWEBSITE_DIR"
    exit 1
fi

COMPONENT=@COMPONENT@

PERSONALWEBSITE_CONFIG_DIR=$ENV_PERSONALWEBSITE_DIR/config
export PERSONALWEBSITE_CONFIG_DIR

LOG4J_CONFIG_FILE_PROPERTY="-Dpersonalwebsite.log4j.file=$PERSONALWEBSITE_CONFIG_DIR/log4j.xml"
COMPONENT_PROPERTY="-Dcomponent=$COMPONENT"
RUNTIME_PROPERTY="-Druntime.properties.dir=$PERSONALWEBSITE_CONFIG_DIR"

export JAVA_OPTS="${LOG4J_CONFIG_FILE_PROPERTY} ${PID_PROPERTY} ${COMPONENT_PROPERTY} ${RUNTIME_PROPERTY}"
